# -*- coding: utf-8 -*-
"""covid data analysis with kmeans clustering .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d5KXXwoTbwyg8F0ZZ3UImfl-VD5axqlm
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler

df=pd.read_csv("/content/DataKasusCoronaIndonesia.csv",parse_dates=["Date"],index_col="Province")
df.columns = df.columns.str.replace(' ','_')
df.head()

class ColumnData:
    date = 'Date'
    province = 'Location'
    island = 'Island'
    cases = 'Total_Cases'
    deaths = 'Total_Deaths'
    recovered = 'Total_Recovered'
    active_cases = 'Total_Active_Cases'
    population = 'Population'
    area = 'Area_(km2)'
    mortality = 'Mortality'
    density = 'Population_Density'

# Mendefinisikan create bins untuk splitting & binning data
def create_bins(df, columns, q=5):
  for column in columns:
   df[column] = pd.qcut(df[column], q, duplicates='drop').cat.codes

# Mendefinisikan normalize_data untuk normalizing data
def normalize_data(df, columns):
    minMaxScaler = MinMaxScaler()
    df[columns] = minMaxScaler.fit_transform(d[columns])

data = df[[
    ColumnData.date,
    ColumnData.province,
    ColumnData.island,
    ColumnData.cases,
    ColumnData.deaths,
    ColumnData.recovered,
    ColumnData.active_cases,
    ColumnData.population,
    ColumnData.area,
    ColumnData.density
]]

#Menghapus jika ada data yang kosong
data = data.dropna(axis=0, how="any")

#Membuat format data pada tanggal menjadi date.
data[ColumnData.date] = pd.to_datetime(data.Date, infer_datetime_format=True).dt.date

#Membuat kolom baru yaitu ‘Mortality’
data[ColumnData.mortality] = data[ColumnData.deaths] / data[ColumnData.cases]

dfl = data[
[ColumnData.date, ColumnData.cases, ColumnData.deaths, ColumnData.recovered]
].groupby(ColumnData.date).sum().reset_index()

dfl = dfl[(dfl[ColumnData.cases] >= 100)].melt(id_vars=ColumnData.date,
value_vars=[ColumnData.cases, ColumnData.deaths, ColumnData.recovered])

#Visualisasi jumlah perkembangan kasus dengan line plot
vis_lp = px.line(dfl, x=ColumnData.date, y='value', color='variable')
vis_lp.update_layout(title='COVID-19 in Indonesia: total number of cases over time',
xaxis_title='Indonesia', yaxis_title='Number of cases',
legend=dict(x=0.02, y=0.98))
vis_lp.show()

pd.options.mode.chained_assignment = None
limit = 5
group = data.groupby(ColumnData.province)
t = group.tail(1).sort_values(ColumnData.cases, ascending=False).set_index(ColumnData.province).drop(
columns=[ColumnData.date])

s = data[(data[ColumnData.province].isin([i for i in t.index[:limit]]))]
s = s[(s[ColumnData.cases] >= 100)]

#vis_lp = visualization line plot
vis_lp2 = px.line(s, x=ColumnData.date, y=ColumnData.cases, color=ColumnData.province)
vis_lp2.update_layout(title='COVID-19 in Indonesia: total number of cases over time',
xaxis_title=ColumnData.date, yaxis_title='Number of cases',
legend_title='<b>Top %s provinces</b>' % limit,
legend=dict(x=0.02, y=0.98))
vis_lp2.show()

heatmap = data[(data[ColumnData.cases] >= 100)].sort_values([ColumnData.date, ColumnData.province])
vis_hmap = go.Figure(data=go.Heatmap(
z=heatmap[ColumnData.cases],
x=heatmap[ColumnData.date],
y=heatmap[ColumnData.province],
colorscale='Viridis'))

vis_hmap.update_layout(
title='COVID-19 in Indonesia: number of cases over time', xaxis_nticks=45)

vis_hmap.show()

t.replace({'Jawa': 0, 'Sulawesi': 1, 'Kalimantan': 2, 'Sumatera': 3, 'Maluku': 4, 'Papua': 5, 'Nusa Tenggara': 6},
inplace=True)

fig, ax = plt.subplots(figsize=(12, 10))
sns.heatmap(t.corr(), vmin=0, cmap='YlGnBu')
plt.show()

corr = t.corr().iloc[[0, 1]].transpose()
corr = corr[(corr[ColumnData.cases] > 0.25)].sort_values(ColumnData.cases, ascending=False)
features = corr.index.tolist()
features.append(ColumnData.mortality)
print('Selected features:', features)

d = t[features].copy()
d.head()

create_bins(d, [
  ColumnData.cases,
  ColumnData.deaths,
  ColumnData.recovered,
  ColumnData.active_cases,
  ColumnData.population,
  ColumnData.mortality,
  ColumnData.density
], q=7)

normalize_data(d, d.columns)
d.head()

#selecting features
X = d[['Mortality', 'Total_Cases','Total_Active_Cases', 'Population_Density', 'Population', 'Total_Deaths']]

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

#Elbow Method - Inertia plot
inertia = []
#looping the inertia calculation for each k
for k in range(1, 10):
    #Assign KMeans as cluster_model
    cluster_model = KMeans(n_clusters = k, random_state = 24)
    #Fit cluster_model to X
    cluster_model.fit(X)
    #Get the inertia value
    inertia_value = cluster_model.inertia_
    #Append the inertia_value to inertia list
    inertia.append(inertia_value)
    ##Inertia plot
plt.plot(range(1, 10), inertia)
plt.title('The Elbow Method - Inertia plot', fontsize = 20)
plt.xlabel('No. of Clusters')
plt.ylabel('WCSS')
plt.show()

kmeans = KMeans(n_clusters=6)
pred = kmeans.fit_predict(d[d.columns])
t['K-means'], d['K-means'] = [pred, pred]
d[d.columns].sort_values(['K-means', ColumnData.mortality, ColumnData.cases, ColumnData.active_cases, ColumnData.density, ColumnData.deaths, ColumnData.population, ColumnData.recovered], ascending=False).style.background_gradient(
cmap='YlGnBu', low=0, high=0.2)
vis_tmap = px.treemap(t.reset_index(), path=['K-means', ColumnData.province], values=ColumnData.cases)
vis_tmap.update_layout(title='K-means clusters by cases')
vis_tmap.show()

vis_tmap = px.treemap(t.reset_index(), path=['K-means', ColumnData.province], values=ColumnData.mortality)
vis_tmap.update_layout(title='K-means clusters by mortality')
vis_tmap.show()

#visualization using bar chart
c = t.sort_values(['K-means', ColumnData.cases], ascending=False)
data = [go.Bar(x=c[(c['K-means'] == i)].index, y=c[(c['K-means'] == i)][ColumnData.cases],
text=c[(c['K-means'] == i)][ColumnData.cases], name=i) for i in range(0, 6)]

vis_bar = go.Figure(data=data)
vis_bar.update_layout(title='K-means Clustering: number of cases by cluster',
xaxis_title='Indonesia State', yaxis_title='Deaths per case')
vis_bar.show()

#visualization mortality rate by clusters
c = t.sort_values(['K-means', ColumnData.mortality], ascending=False)
data = [go.Bar(x=c[(c['K-means'] == i)].index, y=c[(c['K-means'] == i)][ColumnData.mortality],
text=c[(c['K-means'] == i)][ColumnData.mortality], name=i) for i in range(0, 6)]
data.append(
go.Scatter(
  x=t.sort_values(ColumnData.mortality, ascending=False).index,
  y=np.full((1, len(t.index)), 0.03).tolist()[0],
  marker_color='black',
  name='Indonesian avg')
)

vis_bar2 = go.Figure(data=data)
vis_bar2.update_layout(title='K-means Clustering: mortality rate by cluster',
xaxis_title='Indonesian states', yaxis_title='Deaths per case')
vis_bar2.show()

